Universe       = vanilla
Notification   = Error
GetEnv         = True
Initialdir     = $ENV(PWD)
Executable     = /bin/sh
Priority       = +20
Log	         = /gpfs/mnt/gpfs02/eic/kdevereaux/jobs/jobout/log$(Process).log
Output        = /gpfs/mnt/gpfs02/eic/kdevereaux/jobs/jobout/out$(Process).out
#Log            = /dev/null
#Output         = /dev/null
Error          = /dev/null
Requirements   = (CPU_Speed >= 1)

Arguments      = run_chadron_ep.sh $(Process) 0 1 0 1
Queue 500
